admin/rrimporters/onesite/main.go, importers/onesite/constants.go, importers/onesite/loader.go, importers/onesite/people.go, importers/onesite/report.go, importers/onesite/utils.go, rcsv/csvutil.go, rcsv/loadrscsv.go, rcsv/loadrtrate.go, rcsv/loadspratecsv.go
**FIXES**
- updated doc for onesite importer
- fix error pattern raising from rcsv loaders
- count only those report in summary section which are used for importer  (respective to onesite and roomkey) program
- people note field value
=> FIXED Doc for onesite importer, Summary Report 

admin/rrimporters/roomkey/Makefile, importers/roomkey/csv_types.go, importers/roomkey/loader.go, importers/roomkey/rentable.go
Removed unused code from roomkey importer
=> FIX: Remove unused functions

rrpt/util.go, wsvc.go
since now gotable supports dynamic pdf options
=> FIX: define custom rentroll pdf props for pdf reports,

html/home.html, rlib/rfmt.go, rrpt/util.go, uiutil.go, wsvc.go
**FIXES**
- removed dead code
- fixed attachment report name with proper date format
- added options to choose pdf page size and pdf orientation
=> ADDED option to choose pdf page size, orientation

html/home.html, js/rutil.js, test/ws/gold/d.gold, ws/ar.go, ws/asm.go, ws/receipt.go
- show account rule in assessment and receipt grid
- show TCID in payor type down in receipt form
- show ARType in AR grid
- show Rentable Name in assessment grid
=> FIXED bunch of issues

html/formar.html, html/home.html, ws/ar.go, ws/ra.go
- bring out rental agreement of which payor is null
- show debit and credit ledger account in AR grid
- remove Save button from toolbar in assessments, receipts grid
- add more width in rentable column in assessments grid
- show company also as in payor, inside rental agreement grid
- add more width in Payor(s) column in rental agreement grid
- assessment form + bind backend APIs
=> FIXED bunch of issues, please check the list

html/formar.html, html/home.html, js/rutil.js, rlib/rfmt.go, test/ws/functest.sh, test/ws/gold/aa.gold, test/ws/gold/q.gold, test/ws/gold/z.gold, ws/ar.go, ws/gl.go, ws/ra.go, ws/rapayor.go, ws/rt.go, ws/svc.go
- used building icon to indicate that payor is a company.
=> Manage AR resources with CRUD operations API support

db/schema/schema.sql, html/home.html, js/rutil.js, rlib/dbtypes.go, rlib/insert.go, rlib/prepsql.go, rlib/read.go, rlib/update.go, test/jm1/ar.csv, test/ws/gold/aa.gold, ws/ar.go, ws/gl.go
- RARequired field has been added in schema.sql hence ar.csv(test/jm1), rlib/{read, insert, prepsql, update, dbtypes}.go modified
- handled RARequired (Prior To RAStart, Prior to RAStop fields) in AR w2ui form
- fixed the format of GLAccount name: `GLNumber (Name)`
=> ADDED RARequired field in AR table

html/home.html, js/rutil.js, test/ws/gold/a1.gold, test/ws/gold/b1.gold, ws/ajaxlists.go, ws/uival.go
**CHANGES**
- get rid of `eval` function on front-end side
- fixed form field html control binding error on w2ui form
- fixed `uilists`, `uivals` web api
- RAGrid record's payor icon bug (cannot find PayorIsCompany of null fixed)
=> Get rid of eval function + other fixes

html/formacct.html, html/formar.html, html/formr.html, html/formrt.html, html/rentroll.css, js/src/account.js, js/src/ar.js, js/src/asms.js, js/src/datenav.js, js/src/datetimeutil.js, js/src/dep.js, js/src/pmt.js, js/src/receipt.js, js/src/rentable.js, js/src/report.js, js/src/rt.js
- Added w2ui date control in asms, receipts, report section.  
- Added save and add another button in below module.  
1. Chart of account
2. Payment Types
3. Depositories
4. AS rules
5. Rentable type
6. AM Rentables
=> w2ui date control | save and add another button in setup section

webclient/js/elems/layout.js, webclient/js/elems/ra.js, webclient/js/elems/rr.js, webclient/js/elems/rt.js, ws/rr.go
- grid save call in rarGrid
- show manageToBudget error on save of rtForm, when market rate data is not given
- pagination number in rentroll report - first | last | total
- Rental Agreement Form dirty dialog issue
=> FIXED: Pagination in Rentroll report

rrpt/rr.go
… row
1. Don't show repetitive info in Payors, Users column
2. Show PaymentsApplied number with respected Assessment
3. Add Group by clause to collect all assessments,receipts figures
=> Rentroll report fixes in payors, PaymentsApplied columns, grand total

webclient/js/elems/rovreceipt.js
=> rovclient - close the dialog once report is downloaded, align inputs vertically proper

test/webclient/cypress/integration/roller_spec.js, test/webclient/cypress/support/commands.js, test/webclient/cypress/support/components/receipts.js, test/webclient/cypress/support/utils/common.js, test/webclient/cypress/support/utils/constants.js, test/webclient/cypress/support/utils/get_selectors.js, test/webclient/gold/a.gold
In this update below points are covered.
- Handle PmtTypes and Money types fields
- Add changing date steps from the toolbar
- Made code more modular
- Handle BUD/BID dynamically
=> Update: cypress UI Tests for receipt module

db/schema/schema.sql, rlib/rstat.go, webclient/js/elems/rentable.js
1. Don't allow user to set unknown state for existing instance (RSID > 0)
=> rentableStatus grid - add inactive value in use, lease status

test/webclient/cypress/integration/roller_spec.js, test/webclient/cypress/support/components/receipts.js, test/webclient/gold/a.gold
- Added test for visibility checking and matching field value for ERentableName field
=> ADD: Test for ERentableName field in form

test/webclient/Makefile, test/webclient/cypress/integration/roller_spec.js, test/webclient/cypress/support/components/receipts.js, test/webclient/cypress/support/utils/constants.js, test/webclient/functest.sh, test/webclient/gold/a.gold, test/webclient/webclientTest.sql
- Change application cookie name
- Change in loading predefine database for tests (From db4 to custom mysql dump)
- Skip ERentableName filed in receipt form while performing form tests. (Changes in receipt.js)
=> Configuration update for Cypress UI Test for Receipt module

test/Makefile, test/webclient/cypress/support/components/receipts.js, test/webclient/functest.sh, webclient/html/test/combo_field_remote.html, webclient/js/elems/rovreceipt.js
**Other Fixes**
- enabled webclient test cases 
- enabled testing on ERentableName field in cypress, removed it from the list of skipFields
=> receipt only client - ERentableName field type changed from enum to combo

bizlogic/ar.go, bizlogic/bizerr.csv, bizlogic/init.go, webclient/.jshintrc, webclient/html/home.html, webclient/js/elems/ar.js, webclient/js/elems/bpwrapper.js, webclient/js/elems/login.js, webclient/js/elems/rutil.js, webclient/js/elems/sidebar.js
- Account Rule ARType validation in bizlogic
- Selection option added in drop down menu of ARType in arsForm
- minor fixes in login.js
=> several front end issues

test/webclient/README.md, test/webclient/cypress/integration/roller_11_applyreceipt_spec.js, test/webclient/cypress/integration/roller_12_rentabletypes_spec.js, test/webclient/cypress/integration/roller_13_rentable_spec.js, test/webclient/cypress/plugins/index.js, test/webclient/cypress/support/components/rentableTypes.js, test/webclient/cypress/support/components/rentables.js, test/webclient/cypress/support/components/rentroll.js, test/webclient/cypress/support/utils/common.js, test/webclient/cypress/support/wip/roller_14_rentroll_spec.js, test/webclient/gold/a.gold
✓ Grid Records
✓ Record Detail Form
✓ Add new record form
Except: Unpaid assessment grid tests in Apply Receipt detailed form
=> ADD: Cypress UI Tests for Rentables, Rentable Types, Apply Receipt

test/webclient/cypress/integration/receipt_2_spec.js, test/webclient/cypress/integration/roller_14_rentroll_spec.js, test/webclient/cypress/support/components/rentroll.js, test/webclient/cypress/support/utils/common.js, test/webclient/cypress/support/utils/get_selectors.js, test/webclient/gold/a.gold
It covers below scenario:
- Grid records except for User period and Rent period column
- Toolbar section: CSV, PDF, Page Size, Orientation Button
=> ADD: Cypress UI Tests for Rent Roll Section

test/webclient/cypress/support/components/applyreceipt.js, test/webclient/cypress/support/components/ars.js, test/webclient/cypress/support/components/depMeth.js, test/webclient/cypress/support/components/deposits.js, test/webclient/cypress/support/components/expenses.js, test/webclient/cypress/support/components/payorStatements.js, test/webclient/cypress/support/components/pmTypes.js, test/webclient/cypress/support/components/raStatements.js, test/webclient/cypress/support/components/rentableTypes.js, test/webclient/cypress/support/components/rentables.js
- Remove deactivate, reactivate button configuration from `rentables.js`
- Correction in module name in components configuration
=> Remove deactivate button UI tests in Rentables form

test/webclient/cypress/support/components/applyreceipt.js, test/webclient/cypress/support/components/ars.js, test/webclient/cypress/support/components/depMeth.js, test/webclient/cypress/support/components/deposits.js, test/webclient/cypress/support/components/expenses.js, test/webclient/cypress/support/components/payorStatements.js, test/webclient/cypress/support/components/pmTypes.js, test/webclient/cypress/support/components/raStatements.js, test/webclient/cypress/support/components/rentableTypes.js, test/webclient/cypress/support/components/rentables.js, webclient/html/raflow.css, webclient/html/raflowtmpl.html, webclient/js/elems/raflow.js, ws/raflow.go
- `have pets`, `have vehicles` labeled checkbox inside petForm, vehicleForm respectively
- green circle mark for petForm, vehicleForm
- show/hide delete button for pet, vehicle form based on new record
=> Rental Agreement Flow: save/add functionality in pets, vehicles form

.gitignore, Makefile, githooks/pre-commit, linkgithook.sh
Do once `make githook` in the repository to enable pre-commit git hook for the repository.
=> ADD: Configure pre-commit git hook

rlib/get.go, rlib/raflow.go, rlib/raflow_fees.go, rlib/update.go, webclient/html/formtc.html, webclient/html/raflow/formra-addtransactant.html, webclient/html/raflow/formra-fee.html, webclient/html/raflow/formra-vehicles.html, webclient/js/elems/raflow/common.js, webclient/js/elems/raflow/fees.js, webclient/js/elems/raflow/parentchild.js, webclient/js/elems/raflow/people.js, webclient/js/elems/raflow/pets.js, webclient/js/elems/raflow/raactions.js, webclient/js/elems/raflow/rentables.js, webclient/js/elems/raflow/tie.js, webclient/js/elems/raflow/vehicles.js, webclient/js/elems/rutil.js, ws/flow2ra.go, ws/raflow_actions.go, ws/raflow_people.go, ws/raflow_pets.go, ws/raflow_rentables.go, ws/raflow_vehicles.go, ws/svc.go
- Modified form field error message for list inputs
- Close the Background information form while deleting transanctant
- Unselect all selected record when form is being closed
- Update tabindexes in *.html for RAFlow
- sync records on modification of people/rentable records
- fees bug (have to assign RentCycle to get proper calculcate fees)
- remove non-recur fees on change of rent dates
- saving tie/parent child info on change of dropdown selection
- session Check method signature
- reset flow to intial state if data has been modified using `UpdateFlowWithInitState` routine
- fix fee form header issue, effect of on change of AR dropdown (should disable cycle and stop date if rule charge is non-recur)
- fix save/add functionality in pet/vehicles grid
- fix grid refresh in pet section …
=> bug fixes on rental agreement flow

test/raflow/actions/actions_base.sh, webclient/js/elems/raflow/raactions.js
- fix displaying dates issue for firefox
- minor fix to load header footer of action layout only once
- fix raflow actions test count in test report
=>  fix displaying dates issue for firefox
